### ISSUE TITLE
Cannot run program "stty.exe"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Valyrox/lanterna#87]
```
Lanterna is trying to execute program stty.exe and it does not exist at my 
computer windows 8 64.


[s[5001;5001H[6n[u[?1049hException in thread "main" java.io.IOException: 
Cannot run program "stty.exe": CreateProcess error=2, O sistema não pode 
encontrar o arquivo especificado
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:460)
    at com.googlecode.lanterna.terminal.text.CygwinTerminal.exec(CygwinTerminal.java:158)
    at com.googlecode.lanterna.terminal.text.CygwinTerminal.sttyCBreak(CygwinTerminal.java:129)
    at com.googlecode.lanterna.terminal.text.CygwinTerminal.setCBreak(CygwinTerminal.java:101)
    at com.googlecode.lanterna.terminal.text.CygwinTerminal.enterPrivateMode(CygwinTerminal.java:78)
    at com.googlecode.lanterna.screen.Screen.startScreen(Screen.java:202)
    at TCPServerLanterna.main(TCPServerLanterna.java:34)
```

Original issue reported on code.google.com by `miche...@gmail.com` on 23 Oct 2013 at 7:02

**Comment by GoogleCodeExporter** [comment]
```
Okay, are you trying to make a telnet-style TCP server with Lanterna? I know 
it's possible, but I've never done it myself. You may need to create a new 
class extending UnixTerminal or ANSITerminal and prevent it from running some 
OS-specific calls. 

In general, lanterna doesn't support native Windows very well, some limited 
support for the Cygwin terminal.
```

Original comment by `mab...@gmail.com` on 1 Dec 2013 at 2:04
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
It would be nice to know a solution for this problem. I'm using Windows 7 64 
and i'm getting the same error.

Is there someone working on that one?
```

Original comment by `cschu...@gmail.com` on 17 Jan 2014 at 2:20

**Comment by GoogleCodeExporter** [comment]
```
Well, as stated above, native console on Windows isn't very well supported, 
partly because it requires a native library to interact with some of the 
low-level functions and I've tried to keep lanterna 100% native library-free. 

But, you might be seeing this under a different environment, what is your setup?
```

Original comment by `mab...@gmail.com` on 16 Feb 2014 at 7:29

**Comment by GoogleCodeExporter** [comment]
```
This issue has been closed because Google Code is shutting down shortly and all 
issues have been migrated, along with the rest of the project, to GitHub. 
However, notifications will probably not work when updates are made to this 
issue on GitHub so for future updates, please visit 
https://github.com/mabe02/lanterna/issues and subscribe to further updates 
there.

Thank you,
Martin
```

Original comment by `mab...@gmail.com` on 12 Jul 2015 at 7:39
- Changed state: **Duplicate**
